# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store"
  lane :release do
    build_number = prompt(
      text: "Build number: "
    )
    version_number = prompt(
      text: "Marketing version: "
    )
    increment_build_number(
      build_number: build_number
    )
    increment_version_number(
        version_number: version_number
    )
    build_app(
      clean: true,
      scheme: 'Timelord',
      configuration: 'Release',
      export_xcargs: '-allowProvisioningUpdates',
      export_method: 'app-store'
    )
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true,
      automatic_release: false,
      phased_release: true,
      run_precheck_before_submit: false
    )
  end
end
